version: "3.5"

services:
  db:
    image: proofy/postgres-13-bullseye-apb
    restart: always
    environment:
      - POSTGRES_PASSWORD=lDvEFVkVyVpHuCOK9To3
      - POSTGRES_DB=ofbiz
      - POSTGRES_USER=ofbiz
    # ports:
    #   - 5432:5432
    # https://raw.githubusercontent.com/k0lter/autopostgresqlbackup/master/autopostgresqlbackup
    volumes:
      - ofbizpostgresbackup:/var/lib/autopostgresqlbackup
      - ofbizpostgresdata:/var/lib/postgresql/data

  ofbiz:
    image: proofy/ofbiz:20.01
    environment:
      - DB_HOST=db
      - DB_PLATFORM="D"
      - DB_PASSWORD=lDvEFVkVyVpHuCOK9To3
      - DOMAINLIST=localhost,127.0.0.1,192.168.122.21,ofbiz.local

    depends_on:
      - db
    ports:
      - 8443:8443
    volumes:
      - ofbizdata:/ofbiz-framework/runtime
      - ofbizdbconf:/ofbiz-framework/framework/entity/config/
      - ofbizsecconf:/ofbiz-framework/framework/security/config/
    #  - 15005:5005
    command: ["--init"]
    # command: ["/ofbiz-framework/gradlew", "ofbiz --status"]
  
  pgadmin:
    image: dpage/pgadmin4
    enviroment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@serinty.net
      - PGADMIN_DEFAULT_PASSWORD=initpw4sec!
      - PGADMIN_CONFIG_DEFAULT_SERVER=0.0.0.0
    depends:on:
      - db
    ports:
      - 5050:80
    volumes:
      - pgadminwork:/var/lib/pgadmin

volumes:
  ofbizpostgresbackup:
  ofbizpostgresdata:
  ofbizdata:
  ofbizdbconf:
  ofbizsecconf:
  pgadminwork:
